aptible/aptible-cli

- .gitignore
- README.md
- lib/aptible/cli/subcommands/db.rb
- lib/aptible/cli/version.rb
I added a db:execute command, which started as a db:anonymize command and included a bit of other refactoring to support it.  RSpec and Rubocop are passing.
> Adding db:execute command

- lib/aptible/cli/subcommands/apps.rb
This is the same functionality as found in the dashboard.
> Add functionality to scale app up/down to n instances.

- lib/aptible/cli/subcommands/apps.rb
- spec/aptible/cli/subcommands/apps_spec.rb
> Add rudimentary test cases for the 'apps:scale' command.

- lib/aptible/cli/agent.rb
- lib/aptible/cli/helpers/env.rb
- lib/aptible/cli/subcommands/logs.rb
- lib/aptible/cli/subcommands/ps.rb
- spec/aptible/cli/subcommands/ps_spec.rb
Pending changes in Dumptruck...
> aptible ps

- lib/aptible/cli/subcommands/logs.rb
- spec/aptible/cli/subcommands/logs_spec.rb
> Provide helpful error on aptible logs when app has no services (fixes #78)

- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/subcommands/db_spec.rb
Include each URL parameter, explicitly explained.
cc: @colby, relates to aptible/support#197.
> Friendlier db:tunnel output 

- README.md
- lib/aptible/cli/subcommands/ps.rb
- lib/aptible/cli/version.rb
> Add deprecation notice for ps command

- aptible-cli.gemspec
> Require aptible-auth >= 0.11.3

- lib/aptible/cli/helpers/database.rb
- lib/aptible/cli/subcommands/apps.rb
- lib/aptible/cli/subcommands/config.rb
- lib/aptible/cli/subcommands/db.rb
- lib/aptible/cli/subcommands/rebuild.rb
- lib/aptible/cli/subcommands/restart.rb
- spec/aptible/cli/subcommands/apps_spec.rb
View https://github.com/aptible/aptible-resource/issues/30 for rationale, https://github.com/aptible/aptible-cli/issues/172 for timing.
> Use create_XXXX! methods

- bin/aptible
> Don't swallow API errors

- README.md
> Point to Toolbelt page

- .rubocop.yml
- lib/aptible/cli/helpers/token.rb
- lib/aptible/cli/helpers/tunnel.rb
- lib/aptible/cli/version.rb
Add Rubocop fixes that are forward-compatible with newer versions of
Rubocop.
> Rubocop fixes

- lib/aptible/cli/helpers/database.rb
- spec/aptible/cli/subcommands/db_spec.rb
Matches *.aptible.in certs.
cc @fancyremarker @blakepettersson
> Use localhost.aptible.in

- aptible-cli.gemspec
- lib/aptible/cli/helpers/ssh.rb
This needs to be updated to
https://github.com/aptible/aptible-api-ruby/pull/78 before merging
> Verify Dynamic Uno host keys

- lib/aptible/cli/helpers/ssh.rb
(copying over the comment from the patch itself)
Assuming we have a TTY, there are two cases here. Either SSH
itself has a TTY, in which case it is controlling the TTY and
the CLI won't be receiving SIGINT when CTRL+C is pressed, or
SSH has no TTY, in which case the CLI and SSH are sharing the
same process group, and will both receive SIGINT when CTRL+C
is pressed and exit accordingly.
I'm not sure how this *should* work on Windows, but it appears
to work pretty much the same way, except that we'll get an ugly
"Terminate batch job (Y/N)?" prompt in the no-TTY-for-SSH case,
which we're likely to have a hard time handling.
Note that this DOES NOT handle the case where the CLI is sent
SIGINT by another process (as opposed to the line discipline).
In this case, SSH will continue running in …
> Silence CTRL+C stack trace out of aptible logs

- .travis.yml
- README.md
- script/sync-readme-usage
Rebuild locally with:
```
bundle exec script/sync-readme-usage README.md
```
> Enforce usage is kept up to date

- lib/aptible/cli/subcommands/db.rb
This seems to be the culprit, though I'm not sure how to update the spec if that should be done here.
> Fix option for database disk resizing.

- README.md
- lib/aptible/cli/subcommands/backup.rb
- spec/aptible/cli/subcommands/backup_spec.rb
> Add support for cross-environment restore

- aptible-cli.gemspec
To pull in this fix: https://github.com/erikhuda/thor/pull/575
---
cc @UserNotFound - this fixes the issue you ran into here: https://aptible.slack.com/archives/C0GN45N59/p1508457537000162
> Bump Thor to 0.20.0

- lib/aptible/cli/subcommands/db.rb
> Fix db:list output: actually show docker_repo

- lib/aptible/cli/resource_formatter.rb
- lib/aptible/cli/subcommands/apps.rb
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/subcommands/apps_spec.rb
- spec/aptible/cli/subcommands/db_spec.rb
~Is there a good way to test the operation not existing? I couldn't find a way to do that.~
@fancyremarker and @krallin
> Make deprovision operation synchronous and add git_ref/docker_ref to apps command.

- lib/aptible/cli/subcommands/backup.rb
- lib/aptible/cli/version.rb
- spec/aptible/cli/subcommands/backup_spec.rb
Part of a series of changes that enables the restoration from backup of deleted databases.
> Look for backups' databases, even if deleted.

- lib/aptible/cli/resource_formatter.rb
```
[
{
"id": 26,
"description": "26: 2020-12-22 23:31:58 UTC, us-east-1",
"created_at": "2020-12-22 23:31:58 UTC",
"region": "us-east-1",
"size": 10,
"manual": true
},
{
"id": 23,
"description": "23: 2020-12-22 21:07:37 UTC, us-west-1",
"created_at": "2020-12-22 21:07:37 UTC",
"region": "us-west-1",
"size": 10,
"manual": false,
"copied_from": {
"id": 22,
"description": "22: 2020-12-22 21:06:26 UTC, us-east-1",
"created_at": "2020-12-22 21:06:26 UTC",
"region": "us-east-1",
"size": 10,
"manual": false
}
},
{
"id": 22,
"description": "22: 2020-12-22 21:06:26 UTC, us-east-1",
"created_at": "2020-12-22 21:06:26 UTC",
"region": "us-east-1",
"size": 10,
"manual": false
},
...
```
> Show whether or not a backup was manual in the backup:* output

- aptible-cli.gemspec
@UserNotFound : feel free to use or close, if it doesn't work.
> Temporarily pin ffi until ffi/ffi#868 is fixed

- README.md
- lib/aptible/cli/resource_formatter.rb
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/subcommands/db_spec.rb
@UserNotFound since this is almost but not quite in prod, let me know when you want to talk through testing this
CC @mdelaossa - I don't expect you to do anything with this unless you want to use it for testing
Here's a preview of what it looks like:
```
Modifying db1...
INFO -- : Starting Database modify operation with ID: 155
INFO -- : STARTING: Modify volume if needed
INFO -- : WAITING FOR: Modify volume if needed
INFO -- : COMPLETED (after 8.88s): Modify volume if needed
INFO -- : STARTING: Commit disk in API
INFO -- : COMPLETED (after 0.05s): Commit disk in API
{
"id": 21,
"handle": "db1",
"type": "postgresql",
"version": "9.5",
"status": "provisioned",
"connection_url": "REDACTED",
"credentials": [
{
"type": "postgresql",
"connection_url": "REDACTED",
"default": true
}
], …
```
> Support database modification via standalone op and restart op

- lib/aptible/cli/agent.rb
- lib/aptible/cli/helpers/config_path.rb
- lib/aptible/cli/helpers/ssh.rb
- lib/aptible/cli/helpers/token.rb
Issue: https://github.com/aptible/aptible-cli/issues/252
> Add support to override configuration path.

- Gemfile
https://github.blog/2021-09-01-improving-git-protocol-security-github/
> Use HTTPS instead of GIT protocol.

- lib/aptible/cli/helpers/date_helpers.rb
- lib/aptible/cli/version.rb
- spec/aptible/cli/helpers/date_helpers_spec.rb
- spec/aptible/cli/subcommands/maintenance_spec.rb
* Fix time display for maintenance
* Bump version
> Release fixes

- lib/aptible/cli/helpers/app.rb
- lib/aptible/cli/helpers/vhost/option_set_builder.rb
I missed a surprising number of commands this way.
> Missed in helpers declared options

- lib/aptible/cli/helpers/telemetry.rb
fix(telemetry): remove registry options
feat(telemetry): send os info
> fix(telemetry): send json not ruby hash

- Gemfile.lock
- lib/aptible/cli/version.rb
> version bump

- Gemfile.lock
- lib/aptible/cli/helpers/vhost/option_set_builder.rb
- lib/aptible/cli/subcommands/endpoints.rb
- lib/aptible/cli/version.rb
Default to `nil` to have the server determine the appropriate default.
> Update HTTP(S) endpoint shared default
