- lib/aptible/cli/helpers/app.rb
- lib/aptible/cli/subcommands/config.rb
- lib/aptible/cli/subcommands/logs.rb
- lib/aptible/cli/subcommands/rebuild.rb
- lib/aptible/cli/subcommands/restart.rb
- lib/aptible/cli/subcommands/ssh.rb
Adds the option of specifying an app via named remotes, rather than the full app handle, like Heroku's `-r` option.  
If interested in merging, I will add the option to the rest of the commands that already support the `--app` option.
As a matter of style, would you prefer to add that option explicitly, like done below, or create a class method along the lines of `app_option` that adds both the app and remote options at once?  This could be defined in the `Helpers::App` module and automatically extended onto the base via the `included` hook.
Also, wasn't sure how to test this.
> Specify app via named remotes

- lib/aptible/cli/helpers/app.rb
- lib/aptible/cli/version.rb
This makes it much easier to manage multiple Aptible environments. For example, one can define:
```
alias staging="APTIBLE_AUTH_ROOT_URL=https://auth.aptible-staging.com \
APTIBLE_API_ROOT_URL=https://api.aptible-staging.com \
APTIBLE_REMOTE=staging"
```
Then, run (e.g.):
```
staging aptible ssh
```
And there's no longer a need for complex Bash functions like `aptible-staging`.
> Accept ENV["APTIBLE_REMOTE"] to determine remote name

- lib/aptible/cli/agent.rb
- lib/aptible/cli/helpers/operation.rb
- lib/aptible/cli/subcommands/apps.rb
- lib/aptible/cli/subcommands/config.rb
- lib/aptible/cli/subcommands/rebuild.rb
- lib/aptible/cli/subcommands/restart.rb
- spec/aptible/cli/subcommands/apps_spec.rb
SSH-ing into the internal dumptruck service will allow us to forward stdout from operations like restarts, rebuilds, config changes, and service scales.
> Allow attaching to logs for some app operations

- README.md
- lib/aptible/cli/helpers/account.rb
- lib/aptible/cli/subcommands/apps.rb
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/subcommands/db_spec.rb
Fixes https://github.com/aptible/aptible-cli/issues/45
To avoid making too many changes, I named the command `db:list` to fit with the already numerous `db:` commands. More than happy to change the name though.
Also improves the developer UI with the `aptible apps` command by leveraging some of the `db:list` implementation.
Happy holidays! :christmas_tree:
> Add `db:list`

- lib/aptible/cli/agent.rb
- lib/aptible/cli/subcommands/domains.rb
- spec/aptible/cli/subcommands/domains_spec.rb
Get the virtual domain from each vhost for an app.
New commands:
aptible domains: Print out the virtual domain for each vhost associated with an app.
aptible domains:hostnames: Print out the mapping of virtual domains to external hosts for each vhost associated with an app.
> Add command for printing out domains

- lib/aptible/cli/subcommands/db.rb
Output of a `db:create` now looks something like:
```
$ aptible db:create test-db-1 --account healthco
INFO -- : Provisioning postgresql database...
INFO -- : Provisioning an EBS volume...
.....
INFO -- : EBS volume provisioned.
INFO -- : Initializing database...
.......
INFO -- : Database initialized.
INFO -- : Starting database...
INFO -- : Database running.
INFO -- : Waiting on DNS for db-healthco-1.aptible.in to sync...
...............
INFO -- : Database provision successful.
postgresql://aptible:5up3r53cr3t@db-healthco-1.aptible.in:19407/db
```
> Forward database provision logs

- lib/aptible/cli/helpers/app.rb
- lib/aptible/cli/helpers/environment.rb
- lib/aptible/cli/subcommands/apps.rb
- lib/aptible/cli/subcommands/config.rb
- lib/aptible/cli/subcommands/domains.rb
- lib/aptible/cli/subcommands/logs.rb
- lib/aptible/cli/subcommands/ps.rb
- lib/aptible/cli/subcommands/rebuild.rb
- lib/aptible/cli/subcommands/restart.rb
- lib/aptible/cli/subcommands/ssh.rb
- lib/aptible/cli/version.rb
- spec/aptible/cli/subcommands/apps_spec.rb
- spec/aptible/cli/subcommands/domains_spec.rb
* Add `--environment` as option to all methods that accept `--app` as an option (and refactor into `app_options`)
* Infer app without requiring `--environment` where possible (this will allow customers to continue using their old-format Git remote URLs)
> Increase reverse-compatibility of `--environment` changes

- lib/aptible/cli/subcommands/config.rb
> config:unset should be an alias for config:rm

- lib/aptible/cli/subcommands/db.rb
This is similar to https://github.com/aptible/dashboard.aptible.com/pull/560. It's another case where an API client tries to set an attribute it should not have access to (more context in https://github.com/aptible/auth.aptible.com/pull/203).
Note: this doesn't *need* to be changed for us to be able to roll out privileged tokens (the attribute update will silently be ignored).
> Do not update DB status on deprovision

- lib/aptible/cli/subcommands/apps.rb
- spec/aptible/cli/subcommands/apps_spec.rb
The current behavior is to go on and crash at service.create_operation,
which results in a somewhat cryptic error (see ZD 5202). This patch
updates apps:scale to instead explain the problem and display a list of
services that would have been valid.
> apps:scale - Error out when service isn't found

- Gemfile
- lib/aptible/cli/subcommands/apps.rb
- lib/aptible/cli/version.rb
- spec/aptible/cli/subcommands/apps_spec.rb
- spec/aptible/cli/subcommands/domains_spec.rb
- spec/spec_helper.rb
This commit adds an optional --size parameter, which can be used to
set a memory limit on the service that is being scaled, as in the
dashboard. If not specified, the service will either whatever default
it previously had, or whatever Sweetness has set as default.
This commit also adds Webmock to the specs, since there are some
inadvertent calls that are being made to our api.
> Add size option when scaling app

- lib/aptible/cli/helpers/token.rb
For unattended operation, it's easier to pass a token via the
environment rather than generate a JSON file in HOME and remember to
delete it, or use `aptible login`.
This change lets the aptible CLI look for a token in the
APTIBLE_ACCESS_TOKEN environment variable. The variable takes precedence
over the Aptible configuration file to allow for predictable behavior
when running on a host where there is also a configuration file.
In particular, this feature is useful to use the aptible cli in
integration tests.
--
> Check for token in APTIBLE_ACCESS_TOKEN

- README.md
- lib/aptible/cli/subcommands/logs.rb
Because it will soon no longer deprecated!
> Remove deprecation notice for aptible logs

- aptible-cli.gemspec
- lib/aptible/cli/agent.rb
- lib/aptible/cli/helpers/database.rb
- lib/aptible/cli/helpers/tunnel.rb
- lib/aptible/cli/subcommands/db.rb
- lib/aptible/cli/subcommands/logs.rb
- lib/aptible/cli/subcommands/ps.rb
- lib/aptible/cli/subcommands/ssh.rb
- spec/aptible/cli/helpers/tunnel_spec.rb
- spec/aptible/cli/subcommands/db_spec.rb
- spec/mock/ssh_mock.rb
This updates the CLI so that it waits for a message from the backend before reporting the tunnel is ready when using `db:tunnel` and related commands.
The message can either be the `TUNNEL READY` one sent by https://github.com/aptible/broadwayjoe/pull/39, or we could simply roll back the SSH data transport changes and capture `Connected. Ctrl-C to close connection` instead.
This also refactors the way tunnels are stood up a little bit (to take advantage of the fact that the tunnel is now able to report that it's up).
> Signal tunnel ready

- lib/aptible/cli/subcommands/apps.rb
Expecting users to have to guess the git remote (environment handle
included and everything) isn't ideal.
cc @fancyremarker @wcpines (you might want to update the quickstarts once this is live)
> Show git remote when creating app

- spec/spec_helper.rb
cc @blakepettersson — I'm getting the following on each test run otherwise:
```
{"meta": {"status": 400}, "error": {"reason": "Please provide the repository token to upload reports via `-t :repository-token`", "context": null}}
````
> Only report coverage in CI

- aptible-cli.gemspec
- lib/aptible/cli/agent.rb
- lib/aptible/cli/subcommands/backup.rb
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/subcommands/apps_spec.rb
- spec/aptible/cli/subcommands/backup_spec.rb
- spec/aptible/cli/subcommands/db_spec.rb
- spec/aptible/cli/subcommands/domains_spec.rb
- spec/aptible/cli/subcommands/logs_spec.rb
- spec/aptible/cli/subcommands/ps_spec.rb
- spec/fabricators/account_fabricator.rb
- spec/fabricators/app_fabricator.rb
- spec/fabricators/backup_fabricator.rb
- spec/fabricators/database_fabricator.rb
- spec/fabricators/operation_fabricator.rb
- spec/fabricators/service_fabricator.rb
- spec/fabricators/vhost_fabricator.rb
- spec/spec_helper.rb
There are two things in this PR:
- (More important) A few new commands:
- `db:backup HANDLE`: creates a new DB backup.
- `backup:list HANDLE`: lists backups for a DB.
- `backup:restore ID`: restores a backup.
- Refactoring of our specs to use fabricators and reduce the need for stubbing. It doesn't eliminate all stubbing (ideally I'd want to be able to get rid of all the `allow(Aptible::Api::App).to receive(:all) { [app] }`), but it reduces it quite a bit.
Probably worth discussing is the naming of the commands. I feel pretty strongly that we don't want both `db:backup` and `db:backups` (that would be very typo-prone), and I think what I have right now is consistent with some of our other naming conventions (list on the resource being listed — as opposed to the container —, other actions …
> Backups: restore, list, create

- lib/aptible/cli/helpers/app.rb
- lib/aptible/cli/helpers/environment.rb
- spec/aptible/cli/agent_spec.rb
- spec/mock/git
In practice most customers will have git on their PATH, but it's
probably preferable not to fail loading the entire CLI just because git
is not available (especially considering we're able to handle that
gracefully).
cc @fancyremarker @blakepettersson
> Ensure CLI can load without git on the PATH

- lib/aptible/cli/helpers/database.rb
- lib/aptible/cli/helpers/tunnel.rb
- spec/aptible/cli/helpers/tunnel_spec.rb
- spec/mock/ssh_mock.rb
As reported by Diego Argueta, the CLI does not exit when port forwarding
fails because something else is already listening on the port that was
chosen.
The impact of this problem can range from annoying (if another program
races us to open that port) to insecure (if another program is
intentionally hogging the port).
This fixes the issue by setting ExitOnForwardFailure=yes when launching
the tunnel, which makes the SSH client exit rather than fail silently.
In order to make this easy to troubleshoot, we also capture SSH's error
output (and remove the `-q` flag), and dump it as part of our exception
in case the tunnel fails to come up (which requires refactoring the
tests slightly to stop relying on capturing SSH's stderr rather, which
is probably for the best anyway as it makes them fail …
> Tunnel Helper: exit when port forwarding fails

- lib/aptible/cli/subcommands/restart.rb
- spec/aptible/cli/subcommands/restart_spec.rb
This allows users to test how their app reacts to an OOM restart on
Aptible.
See: https://github.com/aptible/sweetness/pull/639
--
cc @fancyremarker  @blakepettersson
> Add --simulate-oom restart flag

- lib/aptible/cli/helpers/tunnel.rb
On Linux, we can send SIGHUP to a dead process without issues, but on
Windows (including "Bash for Windows"), this happens to fail.
In practice, it doesn't really matter if this fails (since the intention
was to stop the process anyway), so we just ignore it.
This is particularly useful since we'll call `stop` if we get an
exception when running `ssh`, and if `stop` fails we'll never get to see
the original exception.
---
cc @blakepettersson
> db:tunnel: ignore Errno::ESRCH when kill'ing ssh

- lib/aptible/cli/helpers/ssh.rb
As noted in https://github.com/aptible/aptible-cli/issues/201, it looks
like SSH's ControlMaster doesn't respect a client's `SendEnv`
directives, which means a single connection can't be shared across
Aptible commands that require different environment variables (like
`aptible ssh` and `aptible db:tunnel`).
One option would be to set the `ControlPath` to something that depends
on the environment variables we plan to allow, which would let users
take advantage of functional AND faster tunnels, but for now the safer
option is probably to disable ControlMaster altogether (so that the
Aptible CLI does not set up a shared connection) and ControlPath (so
that the Aptible CLI dos not attempt to reuse a shared connection).
Fixes: #201 
---
cc @fancyremarker @blakepettersson
> Disable ControlMaster / ControlPath

- lib/aptible/cli/helpers/database.rb
This ensures we'll tell the user why if their clone operation fails.
--
Note: this will get end-to-end test coverage in aptible-integration, so considering we don't have any existing specs for `db:clone`, I'm not going to add any right now.
cc @fancyremarker @blakepettersson
> db:clone: attach to operation logs

- appveyor.yml
- aptible-cli.gemspec
- lib/aptible/cli/helpers/tunnel.rb
- spec/aptible/cli/agent_spec.rb
- spec/aptible/cli/helpers/git_remote_handle_strategy_spec.rb
- spec/aptible/cli/helpers/tunnel_spec.rb
- spec/mock/ssh
- spec/mock/ssh.bat
- spec/shared/mock_ssh_context.rb
- Use win32-process gem to spawn and kill processes.
- `SIGHUP` (or unix signals for that matter) is not supported on
windows - ruby wrapper supports the equivalent of `SIGINT` though, so
use that.
- Since subprocess terminates immediately on windows, there's no need
to wait when stopping tunnel
- Add `new_pgroup` flag, since that seems to be the only way to be able
to `SIGINT` a subprocess. This flag is invalid on *nix, so we have to
ensure it's only used on windows
- ~Add appveyor gem when testing on windows~
> Make db:tunnel more windows-friendly

- lib/aptible/cli/subcommands/db.rb
Silences:
```
Expected string default value for '--size'; got 10 (numeric)
```
See: https://github.com/aptible/pancake/pull/156
---
@fancyremarker, do you think we should include a `Gemfile.lock` in this repo to ensure the [omnibus-aptible-toolbelt](https://github.com/aptible/omnibus-aptible-toolbelt) always gets the same versions for its dependencies?
> Fix Thor warning

- lib/aptible/cli/agent.rb
- lib/aptible/cli/helpers/operation.rb
- lib/aptible/cli/subcommands/operation.rb
- spec/aptible/cli/helpers/operation_spec.rb
- spec/aptible/cli/subcommands/operation_spec.rb
commit e792f687654d564358c891c19c22b39c3eb58854
Author: Thomas Orozco <thomas@orozco.fr>
Date:   Thu Dec 1 13:53:30 2016 +0100
Indicate operation ID when operation failed
There's a lot more detailed output coming out of Sweetness that explains
what to do, it's probably not needed for the aptible CLI to layer on its
own error message.
commit a3262998980b83d8d69cf93b45241ef74f69de53
Author: Thomas Orozco <thomas@orozco.fr>
Date:   Thu Dec 1 13:53:22 2016 +0100
Add aptible operation:cancel OPERATION_ID
This adds the ability to cancel an operation (more specifically: to
request cancellation - only operations that support it will care for
that flag).
Ideally, I'd like this to eventually attach to the operation so you can
see it complete (and to have a matching `aptible operation:attach` …
> Cancel operations

- aptible-cli.gemspec
This gives us https://github.com/aptible/aptible-api-ruby/pull/76, which
ensures that clients can connect to the SSH Portal even if they have too
many unacceptable keys in their SSH Agent keyring.
> Upgrade aptible-api to 0.9.15

- lib/aptible/cli/helpers/ssh.rb
The verbose log level isn't particularly useful when trying to
troubleshoot connection issues, so let's go all the way to DEBUG3 when
APTIBLE_SSH_DEBUG is set
---
> APTIBLE_SSH_VERBOSE -> APTIBLE_SSH_DEBUG

- lib/aptible/cli/helpers/tunnel.rb
It looks like we need to apply more force when shutting down OpenSSH on
Windows, at least when using the Windows fork
(https://github.com/PowerShell/Win32-OpenSSH /
https://github.com/PowerShell/openssh-portable).
Using `SIGINT`, it looks like the OpenSSH process doesn't do anything.
Unfortunately, it appears this causes OpenSSH to not cleanly disconnect
from the server.
This is not ideal, but it's probably acceptable for now since we'll stop
sending keep-alives and the connection should end up shutting down on
the server-side reasonably quickly (about 2 minute later).
---
This should fix part of the issue reported in https://github.com/aptible/aptible-cli/issues/212
> Fix Windows exit tunnel

- aptible-cli.gemspec
- lib/aptible/cli/helpers/database.rb
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/subcommands/db_spec.rb
- spec/fabricators/account_fabricator.rb
- spec/fabricators/database_credential_fabricator.rb
- spec/fabricators/database_fabricator.rb
- spec/fabricators/stack_fabricator.rb
This adds a --type option to `aptible db:tunnel`, which lets users
select a particular database credential (as opposed to just a database)
to connect to, which enables e.g. forwarding the RabbitMQ management UI.
---
cc @fancyremarker 
See: https://github.com/aptible/api.aptible.com/pull/481
> Add support for tunnelling to database credentials

- lib/aptible/cli/helpers/tunnel.rb
- spec/mock/ssh_mock.rb
- spec/shared/mock_ssh_context.rb
This adds support for force-killing the SSH Helper after 5 seconds if it
doesn't exist immediately. This isn't required when running actual
OpenSSH, but when running the mock ssh.bat helper we use in tests, it
usually is (because sending `SIGBRK`, or even `SIGINT` to a console
doesn't always reliably terminate it).
NOTE: I'm leaving around a couple debug helpers in specs if needed in
the future.
---
> Tunnel Helper: Force-kill after 5 seconds

- lib/aptible/cli/helpers/tunnel.rb
- spec/aptible/cli/helpers/tunnel_spec.rb
- spec/mock/ssh_mock.rb
We'll use exitcode 124 to indicate a timeout.
See: https://github.com/aptible/dynamic-uno/pull/12
> Explain tunnel timeouts

- README.md
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/subcommands/db_spec.rb
This adds a db:reload command, which recreates a DB container in-place
(same instance, same mountpoint).
The implementation is very similar to db:backup and I suspect we may
eventually want to merge the two, but considering there were a couple
subtle differences (the log message), I opted to not do so here.
---
> Add a db:reload command

- lib/aptible/cli/subcommands/ssh.rb
- spec/aptible/cli/subcommands/ssh_spec.rb
SSH's default behavior is as follows:
- If a TTY is forced, one is allocated.
- If there is no command, then a TTY is allocated.
- If no-TTY is forced, then none is allocated.
- No TTY is allocated if stdin isn't a TTY.
Unfortunately, in our case, this breaks, because we use a
forced-command, so we don't *ever* send a command, which causes SSH to
*always* allocate TTY, which causes a variety of problems, not least of
which is that stdout and stderr end up merged.
Now, it's pretty common for Aptible users to run commands in their
container with the intention of using a TTY (by e.g. running `aptible
ssh bash`), so we use a slightly different heuristic from SSH: we
allocate TTY iif there's no input or output redirection going on.
End users can always override this behavior with the …
> aptible ssh: Correct TTY handling

- Gemfile
2.x doesn't install on some versions of Ruby we test against, so we can
add this to our Gemfile like we did with ActiveSupport in order to
support those (the CLI works with them either way, though).
> Pin Rack to 1.x

- README.md
- lib/aptible/cli/subcommands/apps.rb
- spec/aptible/cli/subcommands/apps_spec.rb
This changes the aptible apps:scale option format to treat container
count and container size as two "equal" options, rather than always
require container count to be provided as a positional argument and
allow container size to be provided as an afterthought.
To do so, both options are now positional arguments. I have however also
*renamed* one of the options: `--size` is now `--container-size`.
The rationale here is that we also use `--size` for `db:create` and
`backup:restore` in order to reference the size of the disk, but when we
introduce self-service DB scaling, we're going to want to also allow
specifying the container size, and that parameter will have to be named
differently (presumably `--container-size`).
In other words, for the sake of consistency, I'm updating `apps:scale` …
> New apps:scale option format

- lib/aptible/cli/agent.rb
- lib/aptible/cli/subcommands/inspect.rb
- spec/aptible/cli/subcommands/inspect_spec.rb
The goal here is to provide a way for users to access resources exposed
by the API. This command is hidden since our API is not stable.
@fancyremarker I occasionally find myself reaching for a command line this one, and it could be useful for cases where a customer needs to programmatically access one or two fields in an API that's reasonably stable... but obviously it might be a little dangerous to make this an official command before we're able to make API stability guarantees. Let me know what you think.
> Add command: aptible inspect URL

- lib/aptible/cli/subcommands/apps.rb
- lib/aptible/cli/subcommands/backup.rb
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/subcommands/backup_spec.rb
- spec/aptible/cli/subcommands/db_spec.rb
This adds support for a `--container-size` option on `db:create` and
`db:reload`, and adds a new `db:restart` operation that can be used to
resize database containers and disks.
There isn't much going on here, with one notable exception: since we now
allow customers to pass an arbitrary size when creating databases via
`db:create`, we can easily get into a situation where we never attempt
provisioning a database, because the `provision` operation was rejected
in API.
In that case, we'll enqueue a deprovision operation to clean it up.
--
> Add support for database scaling

- lib/aptible/cli/helpers/operation.rb
- lib/aptible/cli/helpers/ssh.rb
- lib/aptible/cli/subcommands/logs.rb
- lib/aptible/cli/subcommands/ps.rb
- lib/aptible/cli/subcommands/ssh.rb
- spec/aptible/cli/helpers/ssh_spec.rb
- spec/aptible/cli/subcommands/logs_spec.rb
- spec/aptible/cli/subcommands/ssh_spec.rb
- spec/script/exit-with
- spec/script/pid-signal
- spec/script/setpgid
- spec/script/ssh-spawn
This was an unfortunate regression introduced in #206: since we'd like
to clean up the certificate after ourselves (even though it'll expire
soon), we can no longer simply use Kernel::exec when running aptible
ssh.
I inadvertently converted this to use Kernel::system instead, but did
not pay attention to the fact that this swallows ssh's exit code. This
patch restores the original behavior. See the inline comments for how /
why it works.
---
cc @fancyremarker - I'll also be adding integration tests in https://github.com/aptible/aptible-integration to make sure we don't regress on this in the future.
> aptible ssh: return command exit code

- README.md
- lib/aptible/cli/agent.rb
- lib/aptible/cli/helpers/app.rb
- lib/aptible/cli/subcommands/config.rb
- lib/aptible/cli/subcommands/deploy.rb
- spec/aptible/cli/subcommands/apps_spec.rb
- spec/aptible/cli/subcommands/deploy_spec.rb
This command can be used in a few ways by customers:
First, it can be used to update an app to deploy from a Docker image (or
update its current Docker image), as well as set environment variables.
```
aptible deploy --app foobar --docker-image httpd:alpine FOO=BAR
```
When this is done, the app's `Dockerfile` will be ignored going forward.
However, other repo files might still influence the deploy.
Specifically, there are two possible cases:
- The app was deployed from git at some point in the past. In this case,
the Docker image deploy will inherit the app's `Procfile` and
`.aptible.yml`, if any. Enclave will fallback to the image's `CMD` as
a `Procfile` substitute if none exists.
- The app was never deployed from `git`. In this case there is no
`Procfile` or `.aptible.yml`, and Enclave …
> Introduce aptible deploy (Direct Docker Deploy)

- lib/aptible/cli/helpers/token.rb
- spec/aptible/cli/helpers/token_spec.rb
This file contains credentials, and should not be readable by other
local users. This fix is UNIX-only, considering that on Windows systems,
a user's home directory should not normally be readable by other users
(whereas that is occasionally the case on UNIX systems, e.g. on Ubuntu).
Fixes this security vulnerability: https://trello.com/c/N7O9D7Dw
---
> Set token file mode to 600

- README.md
- lib/aptible/cli/helpers/database.rb
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/agent_spec.rb
- spec/aptible/cli/subcommands/apps_spec.rb
- spec/aptible/cli/subcommands/db_spec.rb
- spec/aptible/cli/subcommands/deploy_spec.rb
- spec/aptible/cli/subcommands/domains_spec.rb
- spec/aptible/cli/subcommands/logs_spec.rb
Sometimes we want quick access to a database's URL from the command line.
- Add a db:url command
+ Displays the URL for a specified database
* Specify databse with handle
* Raise error if database not found
* Raise error if multiple databases found
+ Sync README.md with new subcommand
- Fix: Replace deprecated `stub` implementations
+ Cleanup "offenses" in test suite (_woops_ 😅 )
* "Shadowing outer local variable - m."
* "Line is too long."
> Add a db:url command

- .travis.yml
- README.md
- script/sync-readme-usage
When first contributing here, I ran into an issue here the README was out of sync after creating a new command. While this is mentioned in the instructions, the command given didn't produce a new output for me. Thus, the build failed.
After looking at the [failing build in TravisCI](https://travis-ci.org/aptible/aptible-cli/builds/266060557), I found that there's an [internal script](https://github.com/aptible/aptible-cli/blob/master/script/sync-readme-usage) with just that purpose: Updating the CLI usage in the readme file. It seemed clear to me that the README should be updated to reference the aforementioned script.
- Sets a default value in README sync script
+ Default to "README.md"
+ Update `.travis.yml` to reflect this change
- Update instructions for syncing README when adding a …
> Update README sync script & Contributing instructions

- README.md
- aptible-cli.gemspec
- lib/aptible/cli/agent.rb
- lib/aptible/cli/helpers/app.rb
- lib/aptible/cli/helpers/app_or_database.rb
- lib/aptible/cli/helpers/vhost.rb
- lib/aptible/cli/helpers/vhost/option_set_builder.rb
- lib/aptible/cli/subcommands/apps.rb
- lib/aptible/cli/subcommands/domains.rb
- lib/aptible/cli/subcommands/endpoints.rb
- lib/aptible/cli/subcommands/logs.rb
- spec/aptible/cli/helpers/vhost_spec.rb
- spec/aptible/cli/subcommands/apps_spec.rb
- spec/aptible/cli/subcommands/endpoints_spec.rb
- spec/fabricators/account_fabricator.rb
- spec/fabricators/app_fabricator.rb
- spec/fabricators/certificate_fabricator.rb
- spec/fabricators/database_fabricator.rb
- spec/fabricators/service_fabricator.rb
- spec/fabricators/vhost_fabricator.rb
Add Endpoint management commands
This adds new Endpoint management commands:
```
aptible endpoints:database:create DATABASE
aptible endpoints:deprovision ENDPOINT_HOSTNAME
aptible endpoints:https:create SERVICE
aptible endpoints:list
aptible endpoints:renew ENDPOINT_HOSTNAME
aptible endpoints:tcp:create SERVICE
aptible endpoints:tls:create SERVICE
```
These commands can be used to create new Endpoints (including the 2 step
process for ACME Endpoints), list them, and delete them.
--
A few notable changes here:
- VHOSTs have a fairly complex set of options, so I've opted to have an
"options-builder" to both declare options and parse them. The main
benefit is that we can test for leftover options we did not expect,
but were given. In turn, this makes our specs much more robust against
typos …
> Endpoints commands

- README.md
- lib/aptible/cli/agent.rb
- lib/aptible/cli/subcommands/services.rb
- spec/aptible/cli/subcommands/services_spec.rb
This command lists services for an app, including their command and
scale.
---
cc @fancyremarker @UserNotFound 
Open question here: do we want to warn when there are no services for an app (because it was never deployed), or keep the output consistent? (this would probably be worth a more generic and concerted effort to update warnings throughout the CLI)
> Add a `aptible services` command

- README.md
- lib/aptible/cli/helpers/database.rb
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/subcommands/db_spec.rb
- spec/fabricators/database_image_fabricator.rb
- spec/fabricators/operation_fabricator.rb
This allows customers to specify a specific Database Image (i.e.
version) when creating a new Database via the CLI.
The db:images command also allows listing available Database Images.
---
This builds upon #241, for the `db:images` command.
See https://github.com/aptible/api.aptible.com/pull/582 for the backend changes
Post release, we should make sure to update the documentation for `db:create` to reference `db:images`.
cc @fancyremarker @UserNotFound
> db:create - add support for --version

- lib/aptible/cli.rb
- spec/aptible/cli_spec.rb
We have at least one customer parsing the output of `db:tunnel`, and
colorizing logs broke their integration, so let's fix this here.
(that said, we should probably consider better scriptability on
`db:tunnel`, the output right now is not even formatted / available as
JSON, and broadly speaking the command does not make it super easy to
access it)
---
> Do not colorize logs without a TTY

- README.md
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/subcommands/db_spec.rb
We want to use the dump command like this:
`aptible db:dump HANDLE --exclude-table-data=events --exclude-table-data=versions`
to not dump data we don't need for our dev env. Not sure if I should have opened an issue first, if I was supposed to sorry!
> Allow to pass options to pg_dump on db:dump

- README.md
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/subcommands/db_spec.rb
https://aptible.zendesk.com/agent/tickets/19602
Also adds `--on-error-stop` flag to `db:execute` to make `psql` stop on error and return a non-zero exit code.
> db:dump and db:execute return non-zero exit codes when postgres command fails

- README.md
- lib/aptible/cli/helpers/database.rb
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/subcommands/db_spec.rb
Closes: https://aptible.atlassian.net/browse/DP-88
Allows for self-service DB replication from the command line:
It will output the operation logs of both the replication step (which is just two unhelpful lines) and the actual provisioning of the DB (which is what you really want to see).
If you try to replicate an unsupported DB type, it will prevent the queueing of the operation:
Without that, it attempts to create the DB for the unsupported type, which ultimately fails to provision correctly. This seemed a cleaner way to handle that, but I'm open to thoughts on that bit.
This is draft as we'll need some documentation updates before this can ship /cc @UserNotFound @joshraker 
There's already an [integration spec](https://github.com/aptible/aptible-integration/blob/master/spec/database/in …
> Support replication creation via the CLI

- README.md
- lib/aptible/cli/subcommands/backup.rb
- lib/aptible/cli/subcommands/inspect.rb
- spec/aptible/cli/subcommands/backup_spec.rb
Part of https://aptible.atlassian.net/browse/DP-202
Adds the backup:purge subcommand to create a `purge` operation on a
specific Backup specified by its ID.
Should not released until https://github.com/aptible/deploy-api/pull/714 is deployed
Example run:
> Adds backup:purge subcommand to purge a single backup by ID

- README.md
- lib/aptible/cli/subcommands/backup.rb
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/subcommands/db_spec.rb
The `--size` option can be ambiguous, so we should prefer a `--disk-size` option.  The `--size` option will remain for compatibility, but will not be documented.
This affects:
* db:create
* db:restart
* db:replicate
* backup:restore
> Prefer "--disk-size" over "--size"

- README.md
- lib/aptible/cli/subcommands/backup.rb
- lib/aptible/cli/version.rb
Backup purge had an incorrect description. This corrects it.
Needs a version bump since we already published the gem to RubyGems even though we never officially released the CLI toolbelt.
> Fix purge description

- aptible-cli.gemspec
- lib/aptible/cli/version.rb
Per https://aptible.slack.com/archives/CJZ7UBMJP/p1589492369030000
Most recent aptible-auth gem `1.2.0` is breaking login via the CLI when installed as a gem. Toolbelt installs are not affected.
This pins the version of the gem until a fix can be released there.
> Pin aptible-auth gem version

- README.md
- lib/aptible/cli/subcommands/backup.rb
Part of https://aptible.atlassian.net/browse/DP-281
If a backup has copies, then the purge operation will remove those.
If a backup is a copy or has no copies, then only that backup will be
removed.
> Clarify that purge will also remove copies

- Gemfile
- README.md
- aptible-cli.gemspec
- lib/aptible/cli/resource_formatter.rb
- lib/aptible/cli/subcommands/backup.rb
- spec/aptible/cli/subcommands/backup_spec.rb
Allows listing "orphaned" backups (i.e. backups of deprovisioned databases, where the backup itself hasn't been purged). Adds in database info, including `deleted_at`, in an attempt to provide maximum context.
Q: Using `deleted_at` is consistent with our API, but not the terminology we use in our docs. I know we're trying to get more consistent about this, but I _also_ know that I want things to match the API. Is there any concerns about this term not matching our docs? I'm happy to make a note about the difference in terminology when updating the docs, if that would be sufficient.
See convo here for context: https://aptible.atlassian.net/jira/software/projects/DP/boards/3?selectedIssue=DP-294
Requires: https://github.com/aptible/aptible-api-ruby/pull/102 (I'm waiting on the merge to …
> CLI command to list backups of deprovisioned databases

- Gemfile
- README.md
- lib/aptible/cli/helpers/database.rb
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/subcommands/db_spec.rb
This will, with corresponding changes to the Deploy API and backend, allow for logical replication of postgres Databases through the Aptible CLI when upgrading versions.
> add CLI flags for logical replication

- .travis.yml
- Gemfile
- README.md
- appveyor.yml
- lib/aptible/cli/helpers/database.rb
- spec/aptible/cli/subcommands/db_spec.rb
- spec/spec_helper.rb
This can't go live until we deploy API, but API has been passing aptible-integration tests, so I suppose that's not really a blocker
> Pull domain from stack, don't default to aptible.in

- aptible-cli.gemspec
- lib/aptible/cli/agent.rb
Part of https://aptible.atlassian.net/browse/DP-354
This adds a warning to the CLI if the user's access to resources is
impacted by their authentication method. If they are part of an SSO
enforced org and logged in with Aptible credentials. Or, conversely,
they are logged in with an SSO token and are part of other orgs.
Right now this prints the warning for any invocation of the CLI. We may
want to limit it so that, e.g. logins, aren't warned about. I'm open to
thoughts on that.
Requires https://github.com/aptible/aptible-auth-ruby/pull/70 to be
published to RubyGems before this work. I'll rerun the Travis tests once
that's done.
------
> Prints a warning if not all Orgs are accessible

- README.md
- lib/aptible/cli/subcommands/backup.rb
EBS supports changing encryption keys when restoring from backup. This gives us two things:
* Custom encryption keys for existing databases (or databases created without them)
* Rotating custom encryption keys
Pairs with https://github.com/aptible/sweetness/pull/1187 (restore behavior is actually broken either way without those changes)
> Allow passing a new KMS CMK ARN when restoring

- bin/aptible
- lib/aptible/cli/agent.rb
- lib/aptible/cli/version.rb
See: https://aptible.slack.com/archives/CJZ7UBMJP/p1604446855018500
This fixes two issues:
1) Our executable was no longer catching the correct error to print the user friendly error message
2) Fetching the token was no longer throwing an error, which was happening during the API call
This fixes both errors:
> Fix token handling

- lib/aptible/cli/resource_formatter.rb
- spec/fabricators/database_disk_fabricator.rb
- spec/fabricators/database_fabricator.rb
Display the disk type and size, as well as container size, and database version when `APTIBLE_OUTPUT_FORMAT=json aptible db:list` is used.
```
[
{
"id": 1,
"handle": "test",
"type": "postgresql",
"version": "13",
"status": "provisioned",
"connection_url": "postgresql://aptible:password@db-test-1.aptible.in:26187/db",
"credentials": [
{
"type": "postgresql",
"connection_url": "postgresql://aptible:password@db-test-1.aptible.in:26187/db",
"default": true
}
],
"environment": {
"id": 1,
"handle": "test"
},
"disk_type": "gp3",
"disk_size": 10,
"container_size": 1024
}
]
```
> Add disk and container attributes to database JSON output.

- lib/aptible/cli/resource_formatter.rb
Database objects are created before the disk and service are - we need to the CLI to return without error in that case.
> Account for databases which have failed to provision.

- lib/aptible/cli/resource_formatter.rb
- spec/fabricators/database_disk_fabricator.rb
Non-critical, deploy any time after API update: https://github.com/aptible/deploy-api/pull/863
This will ensure we show the IOPS for both GP2 and GP3 volume types.
> Use the baseline_iops decorator to account for both GP2 and GP3 volume specs.

- lib/aptible/cli/resource_formatter.rb
Like in the UI, we should show whether the backup was taken manually, and who created the operation, or indicate the backup was automatic, and whether the specific backup is a copy or not.
In the normal output:
In the JSON:
> Show backup operation.

- Gemfile
- aptible-cli.gemspec
- lib/aptible/cli/agent.rb
- lib/aptible/cli/helpers/security_key.rb
- spec/aptible/cli/agent_spec.rb
The goal of this PR is to add support for WebAuthn in `aptible-cli`.  Previously we used the deprecated u2f-api to perform security key based authentication.  Since we migrated away from that in the browser, we also needed to add support in the cli.
Notable changes compared to how it used to work:
- When a user has multiple credentials associated with it, we prompt the user to pick the credential they want to use
- _This is a limitation with how the new [fido2-assert](https://developers.yubico.com/libfido2/Manuals/fido2-assert.html) cli works_
- The user attempts to authenticate using their email and password
- `auth-api` returns an error response indicating the user needs to provide 2fa
- **if** we detect:
- _the user has a valid security credential associated with their account_
- …
> webauthn support

- lib/aptible/cli/subcommands/metric_drain.rb
- spec/aptible/cli/subcommands/metric_drain_spec.rb
Add missing `/api/v1/series` to DD metric drains.
> correct the datadog metric drain url

- lib/aptible/cli/helpers/database.rb
- lib/aptible/cli/subcommands/db.rb
- spec/aptible/cli/helpers/database_spec.rb
- spec/aptible/cli/subcommands/db_spec.rb
Before:
```
$ aptible db:create foo --type cassandra
An error occurred: Validation failed: Database image can't be blank
```
After:
```
$ aptible db:create foo --type cassandra
No Database Image of type "cassandra", valid types: mongodb, mysql, redis, couchdb2, influxdb, elasticsearch, rabbitmq, postgresql, sftp, couchdb
```
> Validate that the database type refers to an existing DatabaseImage.

- aptible-cli.gemspec
- lib/aptible/cli/helpers/s3_log_helpers.rb
- lib/aptible/cli/subcommands/logs.rb
- lib/aptible/cli/version.rb
While we don't support using the aptible-cli gem directly, we, unfortunately, do exactly that in aptible-integration.  By rolling back here, we resolve the dependency issue breaking aptible-integration:
```
Bundler could not find compatible versions for gem "aws-sdk-core":
In Gemfile:
aptible-integration was resolved to 0.0.1, which depends on
aptible-cli was resolved to 0.19.5, which depends on
aws-sdk-core (~> 3.0)
aptible-integration was resolved to 0.0.1, which depends on
aws-sdk (~> 2.0) was resolved to 2.0.1.pre, which depends on
aws-sdk-resources (= 2.0.1.pre) was resolved to 2.0.1.pre, which depends on
aws-sdk-core (= 2.0.1)
```
> Roll back to  older AWS SDK version

- lib/aptible/cli/helpers/s3_log_helpers.rb
Silences the warning when the SDK is loaded when logs_from_archive is used
> Version 2 of the Ruby SDK will enter maintenance mode as of November 20, 2020. To continue receiving service updates and new features, please upgrade to Version 3. More information can be found here: https://aws.amazon.com/blogs/developer/deprecation-schedule-for-aws-sdk-for-ruby-v2/
> Silence AWS sdk warning.

- lib/aptible/cli/subcommands/deploy.rb
Updating the warning to be in line with the actual flag, which is `--git-commitish`
similar to https://github.com/aptible/primetime/pull/74
> Correct --git-commitish typo

- README.md
The current link to https://support.aptible.com/toolbelt results in a 404 - it appears that https://www.aptible.com/docs/cli is the new location for the CLI download link.
> Update download link in README

- lib/aptible/cli/subcommands/metric_drain.rb
Reference: https://docs.datadoghq.com/getting_started/site/
> Add Datadog US5 site

- lib/aptible/cli/resource_formatter.rb
in order to allow a user to use the `aptible backup:list` command to filter out automatic backups which are not yet complete, include the operation information in the JSON output.
> include operations in JSON for automatic backups

- lib/aptible/cli/subcommands/endpoints.rb
* chore: update endpoints doc link
The existing docs link needs updating to [our new docs site](https://www.aptible.com/docs/getting-started/home).
> chore: update endpoints doc link

- Gemfile.lock
- lib/aptible/cli/helpers/environment.rb
- lib/aptible/cli/resource_formatter.rb
- lib/aptible/cli/subcommands/apps.rb
- lib/aptible/cli/subcommands/backup.rb
- lib/aptible/cli/subcommands/config.rb
- lib/aptible/cli/subcommands/db.rb
- lib/aptible/cli/subcommands/environment.rb
- lib/aptible/cli/subcommands/log_drain.rb
- lib/aptible/cli/subcommands/maintenance.rb
- lib/aptible/cli/subcommands/metric_drain.rb
- lib/aptible/cli/version.rb
- spec/aptible/cli/subcommands/apps_spec.rb
- spec/aptible/cli/subcommands/config_spec.rb
- spec/aptible/cli/subcommands/services_spec.rb
Fix misleading error when no environments are available (it used to say there were multiple...) which would occur when a user had no permissions, or before they had completed FTUX.
Support alias `--env` for `--environment` on all commands.
```
[aptible-cli]$ aptible db:list --env chaos
=== chaos
foo
bar
```
Allow an app:scale operation to specify _just_ the container profile option.
Return the container profile in `aptible services` output.
List all backups by default.
> Quality of life requests

- lib/aptible/cli/agent.rb
- lib/aptible/cli/helpers/app.rb
- lib/aptible/cli/helpers/database.rb
- lib/aptible/cli/helpers/environment.rb
- lib/aptible/cli/renderer.rb
- lib/aptible/cli/resource_formatter.rb
- lib/aptible/cli/subcommands/apps.rb
- lib/aptible/cli/subcommands/db.rb
- lib/aptible/cli/subcommands/log_drain.rb
- lib/aptible/cli/subcommands/metric_drain.rb
- spec/aptible/cli/subcommands/apps_spec.rb
- spec/aptible/cli/subcommands/config_spec.rb
- spec/aptible/cli/subcommands/db_spec.rb
- spec/aptible/cli/subcommands/endpoints_spec.rb
- spec/aptible/cli/subcommands/environment_spec.rb
- spec/aptible/cli/subcommands/log_drain_spec.rb
- spec/aptible/cli/subcommands/maintenance_spec.rb
- spec/aptible/cli/subcommands/metric_drain_spec.rb
- spec/aptible/cli/subcommands/services_spec.rb
- spec/fabricators/account_fabricator.rb
- spec/fabricators/app_fabricator.rb
- spec/fabricators/database_fabricator.rb
- spec/fabricators/log_drain_fabricator.rb
- spec/fabricators/metric_drain_fabricator.rb
https://app.shortcut.com/aptible/story/30651/cli-performance-for-list-commands
```bash
$ time bundle exec bin/aptible environment:list
________________________________________________________
Executed in    2.84 secs      fish           external
usr time  426.77 millis    0.25 millis  426.53 millis
sys time  139.25 millis    1.70 millis  137.55 millis
```
```bash
$ time bundle exec bin/aptible environment:list
________________________________________________________
Executed in    2.93 secs      fish           external
usr time  383.18 millis    0.24 millis  382.94 millis
sys time  142.15 millis    1.64 millis  140.51 millis
```
```bash
$ time bundle exec bin/aptible apps
________________________________________________________
Executed in   14.55 secs    fish           external
usr time …
```
> refactor: improve list command performance

- lib/aptible/cli/subcommands/services.rb
Once we release the changes to post-release cooldown, this description should be updated to be more clear for the new understanding of the metric.
> Update defaults and description for post release cooldown
